<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QH7MF66" ignored="0" name="Test1" tests="3" failures="1" timestamp="12 May 2020 12:40:28 GMT" time="68.278" errors="0">
  <testcase name="loginTest" time="42.265" classname="org.xde.Xrefresh.BDD.LoginTest"/>
  <testcase name="loginTest" time="45.621" classname="org.xde.Xrefresh.BDD.LoginTest"/>
  <testcase name="loginTest" time="68.264" classname="org.xde.Xrefresh.BDD.LoginTest">
    <failure type="org.testng.TestNGException" message="java.util.concurrent.ExecutionException: java.lang.NullPointerException">
      <![CDATA[org.testng.TestNGException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
... 13 more
Caused by: java.lang.NullPointerException
at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:303)
at com.aventstack.extentreports.ExtentTest.pass(ExtentTest.java:524)
at org.xde.Xrefresh.ExtentListeners.ExtentListeners.onTestSuccess(ExtentListeners.java:42)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 4 more
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test1 -->
